#!/bin/bash -e

export MACHINE=${MACHINE:-ucm-imx8m-plus}
export _MACHINE=${MACHINE}
EULA=1
T="../sources/meta-boot2qt-compulab/templates"

BD=$(cat <<< $@ | awk '$0=$NF')

if [[ -d ${BD} ]];then

echo "Back to the build environment ${BD}"
source setup-environment.sh ${BD}

else

source setup-environment.sh ${BD}

for _d in ${T}/*;do
	_file=$(basename ${_d})
	for _f in ${_d}/*;do
		cat ${_f} >> conf/${_file}
	done;
done

sed -i "/^#/d;/^$/d" conf/local.conf
sed -i "s/\(MACHINE ??= \).*/\1"\""${_MACHINE}"\""/g" conf/local.conf

fi
